version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_design_patterns
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
